[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Add compat for the config.extra field if the field doesn't exist in config
[[patches]]
[patches.regex]
target = 'functions/misc_functions.lua'
pattern = '''args\.vars\[(?<index>.*)\]'''
position = 'at'
payload = '''args.vars[$index] or (args.vars.extra and args.vars.extra[$index])'''
line_prepend = ''

# If key isn't a number just read then just use the key directly
[[patches]]
[patches.regex]
target = 'functions/misc_functions.lua'
pattern = '''tonumber\(subpart\[1\]\)'''
position = 'at'
payload = '''tonumber(subpart[1]) or subpart[1]'''
line_prepend = ''
